name: configuration for python env
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6
          command: pip install -U pip  # upgrade pip after installing python
      
      - name: create environment
        run: pyenv local 3.8.6 && python -mvenv .venv386

      - name: Install dependencies
        run: pip install -r requirements.txt --upgrade pip

      - name: Analysing the code with flake8
        run: flake8 /home/runner/work/Python/Python/Beginner 

      - name: Linting the code with black
        run: black /home/runner/work/Python/Python/Beginner
